[tool.poetry]
name = "globe"
version = "0.1.0"
description = ""
authors = ["joe.fox <j.oefox@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
